CREATE TABLE [gtn].[CSG_Route] (
    [CSG_SMSRouteID] VARCHAR (50) NOT NULL,
    [WC_RouteId]     VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CSG_Route] PRIMARY KEY CLUSTERED ([CSG_SMSRouteID] ASC)
);

