CREATE LOGIN [user_ext_sap]
    WITH PASSWORD = N'zcqYq@|en.{Ln3YgzdhvsbzbmsFT7_&#$!~<nY,eJ6kiynXj', SID = 0x5BEB34CF7E3B5C479F58792BC1EF7020, DEFAULT_DATABASE = [MessageSphere], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

