CREATE TABLE [sms].[StatSmsLatency] (
    [StatEntryId]        INT             IDENTITY (1, 1) NOT NULL,
    [TimeFrom]           SMALLDATETIME   NOT NULL,
    [Country]            CHAR (2)        NOT NULL,
    [OperatorId]         INT             NULL,
    [ConnUid]            SMALLINT        NULL,
    [Priority]           TINYINT         NOT NULL,
    [SubAccountUid]      INT             NULL,
    [MsgCountTotal]      INT             NOT NULL,
    [MsgCountDelivered]  INT             NOT NULL,
    [SmsCountTotal]      INT             NOT NULL,
    [SmsCountDelivered]  INT             NOT NULL,
    [L3_Min_Latency_sec] DECIMAL (15, 2) NULL,
    [L3_Max_Latency_sec] DECIMAL (15, 2) NULL,
    [L3_Avg_Latency_sec] DECIMAL (15, 2) NULL,
    [L3_Q10_Latency_sec] DECIMAL (15, 2) NULL,
    [L3_Q20_Latency_sec] DECIMAL (15, 2) NULL,
    [L3_Q30_Latency_sec] DECIMAL (15, 2) NULL,
    [L3_Q40_Latency_sec] DECIMAL (15, 2) NULL,
    [L3_Q50_Latency_sec] DECIMAL (15, 2) NULL,
    [L3_Q60_Latency_sec] DECIMAL (15, 2) NULL,
    [L3_Q70_Latency_sec] DECIMAL (15, 2) NULL,
    [L3_Q80_Latency_sec] DECIMAL (15, 2) NULL,
    [L3_Q90_Latency_sec] DECIMAL (15, 2) NULL,
    [L4_Min_Latency_sec] DECIMAL (15, 2) NULL,
    [L4_Max_Latency_sec] DECIMAL (15, 2) NULL,
    [L4_Avg_Latency_sec] DECIMAL (15, 2) NULL,
    [L4_Q10_Latency_sec] DECIMAL (15, 2) NULL,
    [L4_Q20_Latency_sec] DECIMAL (15, 2) NULL,
    [L4_Q30_Latency_sec] DECIMAL (15, 2) NULL,
    [L4_Q40_Latency_sec] DECIMAL (15, 2) NULL,
    [L4_Q50_Latency_sec] DECIMAL (15, 2) NULL,
    [L4_Q60_Latency_sec] DECIMAL (15, 2) NULL,
    [L4_Q70_Latency_sec] DECIMAL (15, 2) NULL,
    [L4_Q80_Latency_sec] DECIMAL (15, 2) NULL,
    [L4_Q90_Latency_sec] DECIMAL (15, 2) NULL,
    [LastUpdatedAt]      DATETIME        NOT NULL,
    [LE2]                INT             NULL,
    [GT2LE5]             INT             NULL,
    [GT5LE10]            INT             NULL,
    [GT10LE20]           INT             NULL,
    [GT20LE30]           INT             NULL,
    [GT30]               INT             NULL,
    CONSTRAINT [PK_StatSmsLatency] PRIMARY KEY CLUSTERED ([StatEntryId] ASC),
    CONSTRAINT [UQ_StatSmsLatency] UNIQUE NONCLUSTERED ([TimeFrom] ASC, [Country] ASC, [OperatorId] ASC, [ConnUid] ASC, [Priority] ASC, [SubAccountUid] ASC)
);

