CREATE TABLE [sms].[StatSmsLogDaily] (
    [Date]                       DATE             CONSTRAINT [DF_StatSmsLogDaily_Date] DEFAULT (sysutcdatetime()) NOT NULL,
    [StatEntryId]                INT              IDENTITY (1, 1) NOT NULL,
    [AccountUid]                 UNIQUEIDENTIFIER NOT NULL,
    [SubAccountUid]              INT              NOT NULL,
    [Country]                    CHAR (2)         NULL,
    [OperatorId]                 INT              NULL,
    [SmsTypeId]                  TINYINT          NOT NULL,
    [ConnUid]                    SMALLINT         NULL,
    [CostCurrency]               CHAR (3)         NOT NULL,
    [Cost]                       REAL             NOT NULL,
    [PriceCurrency]              CHAR (3)         NOT NULL,
    [Price]                      REAL             NOT NULL,
    [SmsCountTotal]              INT              NOT NULL,
    [SmsCountDelivered]          INT              NOT NULL,
    [SmsCountUndelivered]        INT              NOT NULL,
    [SmsCountRejected]           INT              NOT NULL,
    [SmsCountProcessingWavecell] INT              NOT NULL,
    [SmsCountProcessingSupplier] INT              NOT NULL,
    [MsgCountTotal]              INT              NOT NULL,
    [MsgCountDelivered]          INT              NOT NULL,
    [MsgCountUndelivered]        INT              NOT NULL,
    [MsgCountRejected]           INT              NOT NULL,
    [MsgCountProcessingWavecell] INT              NOT NULL,
    [MsgCountProcessingSupplier] INT              NOT NULL,
    [LastUpdatedAt]              DATETIME2 (2)    CONSTRAINT [DF_StatSmsLogDaily_LastUpdatedAt] DEFAULT (sysutcdatetime()) NOT NULL,
    [PriceContract]              DECIMAL (18, 6)  NULL,
    [PriceContractCurrency]      CHAR (3)         NULL,
    [PriceEUR]                   DECIMAL (18, 6)  NULL,
    [CostContract]               DECIMAL (18, 6)  NULL,
    [CostContractCurrency]       CHAR (3)         NULL,
    [CostEUR]                    DECIMAL (18, 6)  NULL,
    [MsgCountConverted]          INT              NULL,
    [SmsCountConverted]          INT              NULL,
    CONSTRAINT [PK_smsStatSmsLogDaily] PRIMARY KEY NONCLUSTERED ([StatEntryId] ASC),
    CONSTRAINT [UIX_smsStatSmsLogDaily_Date_SubAccount_Country_Operator_Conn] UNIQUE NONCLUSTERED ([Date] ASC, [SubAccountUid] ASC, [SmsTypeId] ASC, [Country] ASC, [OperatorId] ASC, [ConnUid] ASC, [CostContractCurrency] ASC, [PriceContractCurrency] ASC),
    CONSTRAINT [UIX_StatSmsLogDaily_Cluster] UNIQUE CLUSTERED ([Date] ASC, [StatEntryId] ASC)
);

