CREATE FUNCTION [dbo].[GetBasePathFromUrl]
(
   @Input NVARCHAR(MAX)
)
RETURNS NVARCHAR(MAX) 
AS
BEGIN
	DECLARE @INDEX_SLASH INT = (CHARINDEX('/', @Input) + 2);
	
	DECLARE @URLs NVARCHAR(MAX) = SUBSTRING(@Input, @INDEX_SLASH, (CHARINDEX('?', @Input + '?', @INDEX_SLASH) - @INDEX_SLASH))
	
	RETURN IIF(RIGHT(@URLs, 1) = '/',  LEFT(@URLs, LEN(@URLs) - 1), @URLs);
END;
